replayio/chromium-skia

src/core/SkFontMgr.cpp, src/core/SkTypeface.cpp, src/fonts/SkFontMgr_indirect.cpp, src/ports/SkFontConfigInterface_direct.cpp, src/ports/SkFontMgr_FontConfigInterface.cpp, src/ports/SkFontMgr_custom.cpp, src/ports/SkFontMgr_fontconfig.cpp
Companion PR to https://github.com/RecordReplay/chromium/pull/30, for https://github.com/RecordReplay/customer-support/issues/30 (chromium's source tree has a bunch of different git repos under it, including one for skia, so we have to create PRs for changes to the separate repositories).
=> Add diagnostics for failure to find default font

src/ports/SkFontConfigInterface_direct.cpp
For https://github.com/RecordReplay/customer-support/issues/30
=> Add more diagnostics for failure to load fonts

src/core/SkScalerCache.cpp
https://linear.app/replay/issue/RUN-488/add-asserts-when-making-glyphs-in-skia-scaler-cache
=> Add asserts when making glyphs in skia scaler cache

src/core/SkScalerCache.cpp
https://linear.app/replay/issue/RUN-580
=> Add more asserts in SkScalerCache

src/core/SkCachedData.cpp, src/core/SkGlyphRunPainter.cpp, src/core/SkResourceCache.cpp, src/core/SkStrikeCache.cpp, src/core/SkVMBlitter.cpp
As for https://github.com/replayio/chromium/pull/159
=> Remove unused recording assertions

src/core/SkTextBlob.cpp
https://linear.app/replay/issue/RUN-769
=> Add assertions when getting text blob intercepts

src/core/SkRecordReplay.cpp, src/core/SkRecordReplay.h, src/core/SkResourceCache.cpp
https://linear.app/replay/issue/RUN-812
=> Allow purging resource cache IDs when events are disallowed

src/core/SkStrikeCache.cpp, src/ports/SkFontHost_FreeType.cpp
https://linear.app/replay/issue/RUN-856
=> Add assertions when looking up strikes

src/core/SkDescriptor.cpp
https://linear.app/replay/issue/RUN-986
=> Add assertion when writing to skia descriptors

src/core/SkResourceCache.cpp
* https://linear.app/replay/issue/RUN-593#comment-6a7eb0f3
* https://linear.app/replay/issue/RUN-1278/asserts-for-skresourcecache
=> Assert SkResourceCache find/add/remove

src/core/SkCachedData.cpp
* https://linear.app/replay/issue/RUN-593#comment-d10e5d6b
=> Asserts for SkCachedData

src/core/SkRecordReplay.cpp, src/core/SkSemaphore.cpp, src/sksl/SkSLPool.cpp
https://linear.app/replay/issue/RUN-1452
=> Support building on windows

src/core/SkCachedData.cpp, src/core/SkResourceCache.cpp
* https://linear.app/replay/issue/RUN-593#comment-710bd8fa
=> RUN-1783: more Skia cache Asserts

src/core/SkBitmap.cpp, src/core/SkCachedData.cpp, src/core/SkPixelRef.cpp, src/core/SkPixmap.cpp
* paired w/ https://github.com/replayio/chromium/pull/607
* https://linear.app/replay/issue/RUN-593#comment-739e094f
=> Assert scalePixels

src/core/SkMessageBus.h, src/core/SkPicture.cpp, src/core/SkPixelRef.cpp, src/image/SkImage.cpp
* paired w/ https://github.com/replayio/chromium/pull/635
* https://linear.app/replay/issue/RUN-593#comment-f01f1a6d
* Tests passed ✔
=> RUN-1883: update Asserts and more leaking

src/core/SkClipStack.cpp, src/core/SkDrawable.cpp, src/core/SkImageFilter.cpp, src/core/SkPathRef.cpp, src/core/SkTextBlob.cpp, src/core/SkTypeface.cpp, src/core/SkVertices.cpp, src/gpu/ResourceKey.cpp, src/gpu/ganesh/ClipStack.cpp, src/gpu/ganesh/GrContextThreadSafeProxy.cpp, src/gpu/ganesh/GrDirectContext.cpp, src/gpu/ganesh/GrGpuResource.cpp, src/gpu/ganesh/GrMemoryPool.cpp, src/gpu/ganesh/GrRenderTask.cpp, src/gpu/ganesh/GrResourceAllocator.cpp, src/gpu/graphite/GraphiteResourceKey.cpp, src/gpu/graphite/Recorder.cpp, src/gpu/graphite/Renderer.cpp, src/image/SkSurface.cpp
* paired w/ https://github.com/replayio/chromium/pull/667
* https://linear.app/replay/issue/RUN-593#comment-2e2eb373
* Tests passed ✔
=> RUN-1969: RecordReplayValue one and assert all other potentially divergent ids

src/ports/SkTypeface_win_dw.cpp
https://linear.app/replay/issue/RUN-2016
WIP
=> Assorted fixes for windows

src/ports/SkFontMgr_win_dw.cpp, src/ports/SkScalerContext_win_dw.cpp, src/ports/SkTypeface_win_dw.cpp
https://linear.app/replay/issue/RUN-2058
=> Add diagnostics for GetAlphaTextureBounds mismatched call

src/ports/SkFontMgr_win_dw.cpp
https://linear.app/replay/issue/RUN-2116
=> Add diagnostics for mismatch while matching font family info

src/ports/SkFontMgr_win_dw.cpp
https://linear.app/replay/issue/RUN-2170
=> Leak StreamFontFileLoader when replaying

src/core/SkFont.cpp, src/core/SkRecordReplay.cpp, src/core/SkRecordReplay.h, src/core/SkStrikeCache.h, src/ports/SkScalerContext_mac_ct.cpp
* paired w/ https://github.com/replayio/chromium/pull/1177
* https://linear.app/replay/issue/TT-822/unknown-call-ctfontcopyattribute#comment-44780270
=> [TT-822] Short-circuit font creation
